# Array of source paths
sources = ["./content/scripts/"]

# Array of symbol paths
symbols = ["./engine/data/symbols/"]

# Whether to enable pointer checking. This adds additional safety but with a
# compile time cost.
check_pointers = true

# Binary file writer configuration
[writer.binary]
# The output path
output = "./engine/data/pack/server"
